version: '2'
services:

  bf-mysql:
    container_name: bf-mysql
    image: mysql/mysql-server:5.6
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=bananafit

  bf-pma:
    container_name: bf-pma
    image: phpmyadmin/phpmyadmin
    links:
      - bf-mysql:db
    ports:
      - "7777:80"

  bf-redis:
    container_name: bf-redis
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

volumes:
  dbdata:
